# docker-compose.yml
version: "3.8"
services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - .:/usr/src/app
        ports:
            - "3000:3000"
            - "6006:6006"
        command: npm run dev
        environment:
            - CHOKIDAR_USEPOLLING=true
