version: "3.8"

services:
    server:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: server
        ports:
            - "4000:4000"
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        command: npm run start:dev
        networks:
            - webnet
        depends_on:
            - mysqldb
            - redis
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379

    redis:
        container_name: redis
        image: redis:5
        command: redis-server
        networks:
            - webnet

    mysqldb:
        container_name: mysqldb
        image: mysql:8
        restart: always
        ports:
            - "3308:3306"
        networks:
            - webnet
        environment:
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - TZ=Asia/Seoul
            - MS_DATA=/var/lib/mysql/data
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        volumes:
            - msdata:/var/lib/mysql

networks:
    webnet:
volumes:
    msdata:
