name: release-autopull
on:
    push:
        branches: release

jobs:
    DISTRIBUTE_API_SERVER:
        name: DISTRIBUTE_API_SERVER
        runs-on: ubuntu-latest
        steps:
            - name: git pull and restart docker for API server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{secrets.REMOTE_IP}}
                  username: ${{secrets.REMOTE_SSH_ID}}
                  password: ${{secrets.REMOTE_PASSWORD}}
                  port: ${{secrets.REMOTE_SSH_PORT}}
                  script: |
                      cd /root/runwithme
                      git pull https://github.com/boostcampwm-2022/WEB26-RunWithMe.git release
                      docker-compose down && docker-compose build --no-cache && docker-compose up -d

    DISTRIBUTE_CHAT_NOTI_SERVER:
        name: DISTRIBUTE_CHAT_NOTI_SERVER
        runs-on: ubuntu-latest
        steps:
            - name: git pull for chat & notification server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{secrets.REMOTE_NOTI_IP}}
                  username: ${{secrets.REMOTE_NOTI_SSH_ID}}
                  password: ${{secrets.REMOTE_NOTI_PASSWORD}}
                  port: ${{secrets.REMOTE_NOTI_SSH_PORT}}
                  script: |
                      cd /root/runwithme
                      git pull https://github.com/boostcampwm-2022/WEB26-RunWithMe.git release

            - name: clean build and restart docker container for notification server
              run: cd noti-server && docker-compose down && docker-compose build --no-cache && docker-compose up -d

            - name: clean build and restart docker container for chat server
              run: cd chat-server && docker-compose down && docker-compose build --no-cache && docker-compose up -d
